export const ADDRESS_LIST_FETCH = 'ADDRESS_LIST_FETCH';
export const ADDRESS_LIST_FETCH_SUCCESS = 'ADDRESS_LIST_FETCH_SUCCESS';
export const ADDRESS_LIST_FETCH_FAIL = 'ADDRESS_LIST_FETCH_FAIL';

export const POINT_ADD = 'POINT_ADD';
export const POINT_REMOVE = 'POINT_REMOVE';
export const POINT_ORDER_CHANGE = 'POINT_ORDER_CHANGE';
export const POINT_POSITION_CHANGE = 'POINT_POSITION_CHANGE';
