export const ADDRESS_LIST_FETCH = 'ADDRESS_LIST_FETCH';
export const ADDRESS_LIST_FETCH_SUCCESS = 'ADDRESS_LIST_FETCH_SUCCESS';
export const ADDRESS_LIST_FETCH_FAIL = 'ADDRESS_LIST_FETCH_FAIL';

export const POINT_ADD = 'POINT_ADD';
export const POINT_REMOVE = 'POINT_REMOVE';
export const POINT_MOVE = 'POINT_MOVE';
